name: "Build for Linux x64"
branding:
  icon: user-check
  color: gray-dark
inputs:
  target:
    required: true
    description: "Rust Target"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.target }}
